name: Docker
on: [push]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build steamrt
        run: make steamrt
      - name: Build proton
        run: make proton
      - name: Login
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push
        run: make push
